// ─────────────────────────────────────────────────────────────────────────
// 스토리 코드젠 (= 템플릿 동기화 스크립트).
//
// 단일 소스: apps/storybook/stories.spec.mjs (컴포넌트별 variant 매트릭스 + 렌더 레시피).
// 여기서 src/generated/*.stories.tsx 를 뽑는다. 스토리는 @comwit/ui-templates 를 "직접 import"
// 하므로 컴포넌트 코드는 어디에도 복제되지 않는다 — 스펙만 고치고 `pnpm stories` 로 재생성한다.
// (variant 를 추가하려면 stories.spec.mjs 만 수정 → 재생성. 스토리를 손으로 반복 작성하지 않는다.)
// ─────────────────────────────────────────────────────────────────────────
import { writeFileSync, mkdirSync, rmSync, readdirSync } from 'node:fs'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url)) // apps/storybook/scripts
const outDir = join(here, '..', 'src', 'generated')
const specsDir = join(here, '..', 'specs')
const tplUiDir = join(
  here,
  '..',
  '..',
  '..',
  'packages',
  'ui',
  'templates',
  'src',
  'components',
  'ui'
)

// 스펙 조각 수집: specs/*.mjs 각 파일이 `export const specs = [...]` 를 내보낸다.
// 컴포넌트별로 파일을 나눠 병렬 편집·충돌 없이 관리한다.
const specFiles = readdirSync(specsDir)
  .filter((f) => f.endsWith('.mjs'))
  .sort()
const specs = []
for (const f of specFiles) {
  const mod = await import(pathToFileURL(join(specsDir, f)).href)
  if (Array.isArray(mod.specs)) specs.push(...mod.specs)
  else if (mod.spec) specs.push(mod.spec)
}

// 실제 존재하는 템플릿 컴포넌트 목록 — 스펙이 이걸 전부 덮는지 감사한다.
const templateFiles = readdirSync(tplUiDir)
  .filter((f) => f.endsWith('.tsx'))
  .map((f) => f.replace(/\.tsx$/, ''))
  .sort()

function pascal(name) {
  return name
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}

function indent(code, pad = '      ') {
  return code
    .trim()
    .split('\n')
    .map((line) => (line ? pad + line : line))
    .join('\n')
}

function renderStory(story) {
  const name = story.name
  // renderFn: 훅(useState/useForm 등)이 필요한 스토리 — 전체 함수 본문(return 포함)을 그대로 넣는다.
  // render:  단순 JSX 표현식 — () => (JSX) 로 감싼다.
  const body = story.renderFn
    ? `() => {\n${indent(story.renderFn, '    ')}\n  }`
    : story.render.includes('\n')
      ? `() => (\n${indent(story.render)}\n    )`
      : `() => (${story.render.trim()})`
  const docs = story.description
    ? `\n  parameters: { docs: { description: { story: ${JSON.stringify(story.description)} } } },`
    : ''
  return `export const ${name}: Story = {\n  render: ${body},${docs}\n}`
}

function buildFile(spec) {
  const importLines = spec.imports
    .map((im) => `import { ${im.names.join(', ')} } from '${im.from}'`)
    .join('\n')
  const extra = (spec.extraImports ?? []).join('\n')
  const metaComponent = spec.component ? `\n  component: ${spec.component},` : ''
  const stories = spec.stories.map(renderStory).join('\n\n')
  return `// AUTO-GENERATED by scripts/build-stories.mjs — DO NOT EDIT. Edit stories.spec.mjs and run \`pnpm stories\`.
import type { Meta, StoryObj } from '@storybook/react-vite'
${importLines}${extra ? '\n' + extra : ''}

const meta = {
  title: 'Components/${spec.title}',${metaComponent}
} satisfies Meta<${spec.component ? `typeof ${spec.component}` : 'unknown'}>

export default meta
type Story = StoryObj<typeof meta>

${stories}
`
}

// 재생성
rmSync(outDir, { recursive: true, force: true })
mkdirSync(outDir, { recursive: true })

const covered = new Set()
for (const spec of specs) {
  const file = join(outDir, `${spec.slug ?? spec.title.toLowerCase()}.stories.tsx`)
  writeFileSync(file, buildFile(spec))
  for (const c of spec.covers ?? [spec.slug ?? spec.title.toLowerCase()]) covered.add(c)
}

// 커버리지 감사 — 스펙이 빠뜨린 템플릿 컴포넌트를 알린다(조용한 누락 방지).
const missing = templateFiles.filter((f) => !covered.has(f))
console.log(
  `stories: ${specs.length} spec(s) → ${specs.length} generated file(s) in src/generated/`
)
if (missing.length) {
  console.log(`⚠ 스펙이 덮지 않은 템플릿 컴포넌트 ${missing.length}개: ${missing.join(', ')}`)
} else {
  console.log(`✓ 모든 템플릿 컴포넌트(${templateFiles.length})가 스펙에 커버됨`)
}
