'use client'

// Generated by scripts/generate.mjs. Edit src/definitions instead.
import { createAnimatedIcon } from './create-animated-icon'
import {
  AlertCircleAnimatedDefinition,
  AlertTriangleAnimatedDefinition,
  ArrowDownAnimatedDefinition,
  ArrowLeftAnimatedDefinition,
  ArrowRightAnimatedDefinition,
  ArrowUpAnimatedDefinition,
  ArrowUpRightAnimatedDefinition,
  BellAnimatedDefinition,
  BriefcaseAnimatedDefinition,
  CalendarDaysAnimatedDefinition,
  CheckAnimatedDefinition,
  CheckCircle2AnimatedDefinition,
  ChevronDownAnimatedDefinition,
  ChevronLeftAnimatedDefinition,
  ChevronRightAnimatedDefinition,
  ChevronsUpDownAnimatedDefinition,
  Clock3AnimatedDefinition,
  CopyAnimatedDefinition,
  CreditCardAnimatedDefinition,
  DatabaseAnimatedDefinition,
  DownloadAnimatedDefinition,
  ExternalLinkAnimatedDefinition,
  FileTextAnimatedDefinition,
  FolderAnimatedDefinition,
  Globe2AnimatedDefinition,
  GraduationCapAnimatedDefinition,
  HeartAnimatedDefinition,
  HouseAnimatedDefinition,
  ImagePlusAnimatedDefinition,
  KeyRoundAnimatedDefinition,
  Link2AnimatedDefinition,
  Loader2AnimatedDefinition,
  LockAnimatedDefinition,
  LockKeyholeAnimatedDefinition,
  LogOutAnimatedDefinition,
  MapPinAnimatedDefinition,
  MenuAnimatedDefinition,
  MessageCircleAnimatedDefinition,
  MessagesSquareAnimatedDefinition,
  MoreHorizontalAnimatedDefinition,
  PencilAnimatedDefinition,
  PlusAnimatedDefinition,
  RefreshCcwAnimatedDefinition,
  RefreshCwAnimatedDefinition,
  RocketAnimatedDefinition,
  RotateCcwAnimatedDefinition,
  SearchAnimatedDefinition,
  SendAnimatedDefinition,
  SettingsAnimatedDefinition,
  Share2AnimatedDefinition,
  ShieldCheckAnimatedDefinition,
  SlidersHorizontalAnimatedDefinition,
  SmartphoneAnimatedDefinition,
  SparklesAnimatedDefinition,
  StarAnimatedDefinition,
  Trash2AnimatedDefinition,
  UploadAnimatedDefinition,
  UserRoundAnimatedDefinition,
  UsersAnimatedDefinition,
  XAnimatedDefinition,
} from './generated/definitions'
export { AnimatedIcon } from './create-animated-icon'
export type { AnimatedIconProps } from './types'

export const AnimatedAlertCircleIcon = /* @__PURE__ */ createAnimatedIcon(
  AlertCircleAnimatedDefinition
)
export const AnimatedAlertTriangleIcon = /* @__PURE__ */ createAnimatedIcon(
  AlertTriangleAnimatedDefinition
)
export const AnimatedArrowDownIcon = /* @__PURE__ */ createAnimatedIcon(ArrowDownAnimatedDefinition)
export const AnimatedArrowLeftIcon = /* @__PURE__ */ createAnimatedIcon(ArrowLeftAnimatedDefinition)
export const AnimatedArrowRightIcon = /* @__PURE__ */ createAnimatedIcon(
  ArrowRightAnimatedDefinition
)
export const AnimatedArrowUpIcon = /* @__PURE__ */ createAnimatedIcon(ArrowUpAnimatedDefinition)
export const AnimatedArrowUpRightIcon = /* @__PURE__ */ createAnimatedIcon(
  ArrowUpRightAnimatedDefinition
)
export const AnimatedBellIcon = /* @__PURE__ */ createAnimatedIcon(BellAnimatedDefinition)
export const AnimatedBriefcaseIcon = /* @__PURE__ */ createAnimatedIcon(BriefcaseAnimatedDefinition)
export const AnimatedCalendarDaysIcon = /* @__PURE__ */ createAnimatedIcon(
  CalendarDaysAnimatedDefinition
)
export const AnimatedCheckIcon = /* @__PURE__ */ createAnimatedIcon(CheckAnimatedDefinition)
export const AnimatedCheckCircle2Icon = /* @__PURE__ */ createAnimatedIcon(
  CheckCircle2AnimatedDefinition
)
export const AnimatedChevronDownIcon = /* @__PURE__ */ createAnimatedIcon(
  ChevronDownAnimatedDefinition
)
export const AnimatedChevronLeftIcon = /* @__PURE__ */ createAnimatedIcon(
  ChevronLeftAnimatedDefinition
)
export const AnimatedChevronRightIcon = /* @__PURE__ */ createAnimatedIcon(
  ChevronRightAnimatedDefinition
)
export const AnimatedChevronsUpDownIcon = /* @__PURE__ */ createAnimatedIcon(
  ChevronsUpDownAnimatedDefinition
)
export const AnimatedClock3Icon = /* @__PURE__ */ createAnimatedIcon(Clock3AnimatedDefinition)
export const AnimatedCopyIcon = /* @__PURE__ */ createAnimatedIcon(CopyAnimatedDefinition)
export const AnimatedCreditCardIcon = /* @__PURE__ */ createAnimatedIcon(
  CreditCardAnimatedDefinition
)
export const AnimatedDatabaseIcon = /* @__PURE__ */ createAnimatedIcon(DatabaseAnimatedDefinition)
export const AnimatedDownloadIcon = /* @__PURE__ */ createAnimatedIcon(DownloadAnimatedDefinition)
export const AnimatedExternalLinkIcon = /* @__PURE__ */ createAnimatedIcon(
  ExternalLinkAnimatedDefinition
)
export const AnimatedFileTextIcon = /* @__PURE__ */ createAnimatedIcon(FileTextAnimatedDefinition)
export const AnimatedFolderIcon = /* @__PURE__ */ createAnimatedIcon(FolderAnimatedDefinition)
export const AnimatedGlobe2Icon = /* @__PURE__ */ createAnimatedIcon(Globe2AnimatedDefinition)
export const AnimatedGraduationCapIcon = /* @__PURE__ */ createAnimatedIcon(
  GraduationCapAnimatedDefinition
)
export const AnimatedHeartIcon = /* @__PURE__ */ createAnimatedIcon(HeartAnimatedDefinition)
export const AnimatedHouseIcon = /* @__PURE__ */ createAnimatedIcon(HouseAnimatedDefinition)
export const AnimatedImagePlusIcon = /* @__PURE__ */ createAnimatedIcon(ImagePlusAnimatedDefinition)
export const AnimatedKeyRoundIcon = /* @__PURE__ */ createAnimatedIcon(KeyRoundAnimatedDefinition)
export const AnimatedLink2Icon = /* @__PURE__ */ createAnimatedIcon(Link2AnimatedDefinition)
export const AnimatedLoader2Icon = /* @__PURE__ */ createAnimatedIcon(Loader2AnimatedDefinition)
export const AnimatedLockIcon = /* @__PURE__ */ createAnimatedIcon(LockAnimatedDefinition)
export const AnimatedLockKeyholeIcon = /* @__PURE__ */ createAnimatedIcon(
  LockKeyholeAnimatedDefinition
)
export const AnimatedLogOutIcon = /* @__PURE__ */ createAnimatedIcon(LogOutAnimatedDefinition)
export const AnimatedMapPinIcon = /* @__PURE__ */ createAnimatedIcon(MapPinAnimatedDefinition)
export const AnimatedMenuIcon = /* @__PURE__ */ createAnimatedIcon(MenuAnimatedDefinition)
export const AnimatedMessageCircleIcon = /* @__PURE__ */ createAnimatedIcon(
  MessageCircleAnimatedDefinition
)
export const AnimatedMessagesSquareIcon = /* @__PURE__ */ createAnimatedIcon(
  MessagesSquareAnimatedDefinition
)
export const AnimatedMoreHorizontalIcon = /* @__PURE__ */ createAnimatedIcon(
  MoreHorizontalAnimatedDefinition
)
export const AnimatedPencilIcon = /* @__PURE__ */ createAnimatedIcon(PencilAnimatedDefinition)
export const AnimatedPlusIcon = /* @__PURE__ */ createAnimatedIcon(PlusAnimatedDefinition)
export const AnimatedRefreshCcwIcon = /* @__PURE__ */ createAnimatedIcon(
  RefreshCcwAnimatedDefinition
)
export const AnimatedRefreshCwIcon = /* @__PURE__ */ createAnimatedIcon(RefreshCwAnimatedDefinition)
export const AnimatedRocketIcon = /* @__PURE__ */ createAnimatedIcon(RocketAnimatedDefinition)
export const AnimatedRotateCcwIcon = /* @__PURE__ */ createAnimatedIcon(RotateCcwAnimatedDefinition)
export const AnimatedSearchIcon = /* @__PURE__ */ createAnimatedIcon(SearchAnimatedDefinition)
export const AnimatedSendIcon = /* @__PURE__ */ createAnimatedIcon(SendAnimatedDefinition)
export const AnimatedSettingsIcon = /* @__PURE__ */ createAnimatedIcon(SettingsAnimatedDefinition)
export const AnimatedShare2Icon = /* @__PURE__ */ createAnimatedIcon(Share2AnimatedDefinition)
export const AnimatedShieldCheckIcon = /* @__PURE__ */ createAnimatedIcon(
  ShieldCheckAnimatedDefinition
)
export const AnimatedSlidersHorizontalIcon = /* @__PURE__ */ createAnimatedIcon(
  SlidersHorizontalAnimatedDefinition
)
export const AnimatedSmartphoneIcon = /* @__PURE__ */ createAnimatedIcon(
  SmartphoneAnimatedDefinition
)
export const AnimatedSparklesIcon = /* @__PURE__ */ createAnimatedIcon(SparklesAnimatedDefinition)
export const AnimatedStarIcon = /* @__PURE__ */ createAnimatedIcon(StarAnimatedDefinition)
export const AnimatedTrash2Icon = /* @__PURE__ */ createAnimatedIcon(Trash2AnimatedDefinition)
export const AnimatedUploadIcon = /* @__PURE__ */ createAnimatedIcon(UploadAnimatedDefinition)
export const AnimatedUserRoundIcon = /* @__PURE__ */ createAnimatedIcon(UserRoundAnimatedDefinition)
export const AnimatedUsersIcon = /* @__PURE__ */ createAnimatedIcon(UsersAnimatedDefinition)
export const AnimatedXIcon = /* @__PURE__ */ createAnimatedIcon(XAnimatedDefinition)
