'use client'

// Generated by scripts/generate.mjs. Edit src/definitions instead.
import { createAnimatedIcon } from './create-animated-icon'
import {
  AlertCircleAnimatedDefinition,
  AlertTriangleAnimatedDefinition,
  ArrowDownAnimatedDefinition,
  ArrowLeftAnimatedDefinition,
  ArrowRightAnimatedDefinition,
  ArrowUpAnimatedDefinition,
  ArrowUpRightAnimatedDefinition,
  BadgeCheckAnimatedDefinition,
  BellAnimatedDefinition,
  BellRingAnimatedDefinition,
  BookmarkAnimatedDefinition,
  BotAnimatedDefinition,
  BriefcaseAnimatedDefinition,
  Building2AnimatedDefinition,
  CalendarDaysAnimatedDefinition,
  CameraAnimatedDefinition,
  CheckAnimatedDefinition,
  CheckCircle2AnimatedDefinition,
  ChevronDownAnimatedDefinition,
  ChevronLeftAnimatedDefinition,
  ChevronRightAnimatedDefinition,
  ChevronsUpDownAnimatedDefinition,
  ChevronUpAnimatedDefinition,
  ClockAnimatedDefinition,
  Clock3AnimatedDefinition,
  CloudUploadAnimatedDefinition,
  Code2AnimatedDefinition,
  CoffeeAnimatedDefinition,
  CopyAnimatedDefinition,
  CreditCardAnimatedDefinition,
  CrownAnimatedDefinition,
  DatabaseAnimatedDefinition,
  DownloadAnimatedDefinition,
  ExternalLinkAnimatedDefinition,
  EyeAnimatedDefinition,
  EyeOffAnimatedDefinition,
  FileTextAnimatedDefinition,
  FilterAnimatedDefinition,
  FlagAnimatedDefinition,
  FolderAnimatedDefinition,
  FolderGit2AnimatedDefinition,
  FolderKanbanAnimatedDefinition,
  FolderOpenAnimatedDefinition,
  GitBranchAnimatedDefinition,
  GlobeAnimatedDefinition,
  Globe2AnimatedDefinition,
  GraduationCapAnimatedDefinition,
  HeartAnimatedDefinition,
  HistoryAnimatedDefinition,
  HouseAnimatedDefinition,
  ImagePlusAnimatedDefinition,
  InfoAnimatedDefinition,
  KeyRoundAnimatedDefinition,
  LayoutGridAnimatedDefinition,
  Link2AnimatedDefinition,
  Loader2AnimatedDefinition,
  LockAnimatedDefinition,
  LockKeyholeAnimatedDefinition,
  LogInAnimatedDefinition,
  LogOutAnimatedDefinition,
  MailAnimatedDefinition,
  MapPinAnimatedDefinition,
  Maximize2AnimatedDefinition,
  MegaphoneAnimatedDefinition,
  MenuAnimatedDefinition,
  MessageCircleAnimatedDefinition,
  MessageSquareAnimatedDefinition,
  MessagesSquareAnimatedDefinition,
  MicAnimatedDefinition,
  MinusAnimatedDefinition,
  MonitorCogAnimatedDefinition,
  MoonAnimatedDefinition,
  MoreHorizontalAnimatedDefinition,
  PaperclipAnimatedDefinition,
  PauseAnimatedDefinition,
  PencilAnimatedDefinition,
  PenLineAnimatedDefinition,
  PlayAnimatedDefinition,
  PlusAnimatedDefinition,
  RefreshCcwAnimatedDefinition,
  RefreshCwAnimatedDefinition,
  RocketAnimatedDefinition,
  RotateCcwAnimatedDefinition,
  SaveAnimatedDefinition,
  SearchAnimatedDefinition,
  SendAnimatedDefinition,
  ServerCogAnimatedDefinition,
  SettingsAnimatedDefinition,
  Share2AnimatedDefinition,
  ShieldCheckAnimatedDefinition,
  SlidersHorizontalAnimatedDefinition,
  SmartphoneAnimatedDefinition,
  SparklesAnimatedDefinition,
  SquareKanbanAnimatedDefinition,
  SquareTerminalAnimatedDefinition,
  StarAnimatedDefinition,
  SunAnimatedDefinition,
  ThumbsUpAnimatedDefinition,
  Trash2AnimatedDefinition,
  UploadAnimatedDefinition,
  UserPlusAnimatedDefinition,
  UserRoundAnimatedDefinition,
  UsersAnimatedDefinition,
  Volume2AnimatedDefinition,
  WifiAnimatedDefinition,
  WrenchAnimatedDefinition,
  XAnimatedDefinition,
  XCircleAnimatedDefinition,
  ZapAnimatedDefinition,
} from './generated/definitions'
export { AnimatedIcon } from './create-animated-icon'
export type { AnimatedIconProps } from './types'

export const AnimatedAlertCircleIcon = /* @__PURE__ */ createAnimatedIcon(
  AlertCircleAnimatedDefinition
)
export const AnimatedAlertTriangleIcon = /* @__PURE__ */ createAnimatedIcon(
  AlertTriangleAnimatedDefinition
)
export const AnimatedArrowDownIcon = /* @__PURE__ */ createAnimatedIcon(ArrowDownAnimatedDefinition)
export const AnimatedArrowLeftIcon = /* @__PURE__ */ createAnimatedIcon(ArrowLeftAnimatedDefinition)
export const AnimatedArrowRightIcon = /* @__PURE__ */ createAnimatedIcon(
  ArrowRightAnimatedDefinition
)
export const AnimatedArrowUpIcon = /* @__PURE__ */ createAnimatedIcon(ArrowUpAnimatedDefinition)
export const AnimatedArrowUpRightIcon = /* @__PURE__ */ createAnimatedIcon(
  ArrowUpRightAnimatedDefinition
)
export const AnimatedBadgeCheckIcon = /* @__PURE__ */ createAnimatedIcon(
  BadgeCheckAnimatedDefinition
)
export const AnimatedBellIcon = /* @__PURE__ */ createAnimatedIcon(BellAnimatedDefinition)
export const AnimatedBellRingIcon = /* @__PURE__ */ createAnimatedIcon(BellRingAnimatedDefinition)
export const AnimatedBookmarkIcon = /* @__PURE__ */ createAnimatedIcon(BookmarkAnimatedDefinition)
export const AnimatedBotIcon = /* @__PURE__ */ createAnimatedIcon(BotAnimatedDefinition)
export const AnimatedBriefcaseIcon = /* @__PURE__ */ createAnimatedIcon(BriefcaseAnimatedDefinition)
export const AnimatedBuilding2Icon = /* @__PURE__ */ createAnimatedIcon(Building2AnimatedDefinition)
export const AnimatedCalendarDaysIcon = /* @__PURE__ */ createAnimatedIcon(
  CalendarDaysAnimatedDefinition
)
export const AnimatedCameraIcon = /* @__PURE__ */ createAnimatedIcon(CameraAnimatedDefinition)
export const AnimatedCheckIcon = /* @__PURE__ */ createAnimatedIcon(CheckAnimatedDefinition)
export const AnimatedCheckCircle2Icon = /* @__PURE__ */ createAnimatedIcon(
  CheckCircle2AnimatedDefinition
)
export const AnimatedChevronDownIcon = /* @__PURE__ */ createAnimatedIcon(
  ChevronDownAnimatedDefinition
)
export const AnimatedChevronLeftIcon = /* @__PURE__ */ createAnimatedIcon(
  ChevronLeftAnimatedDefinition
)
export const AnimatedChevronRightIcon = /* @__PURE__ */ createAnimatedIcon(
  ChevronRightAnimatedDefinition
)
export const AnimatedChevronsUpDownIcon = /* @__PURE__ */ createAnimatedIcon(
  ChevronsUpDownAnimatedDefinition
)
export const AnimatedChevronUpIcon = /* @__PURE__ */ createAnimatedIcon(ChevronUpAnimatedDefinition)
export const AnimatedClockIcon = /* @__PURE__ */ createAnimatedIcon(ClockAnimatedDefinition)
export const AnimatedClock3Icon = /* @__PURE__ */ createAnimatedIcon(Clock3AnimatedDefinition)
export const AnimatedCloudUploadIcon = /* @__PURE__ */ createAnimatedIcon(
  CloudUploadAnimatedDefinition
)
export const AnimatedCode2Icon = /* @__PURE__ */ createAnimatedIcon(Code2AnimatedDefinition)
export const AnimatedCoffeeIcon = /* @__PURE__ */ createAnimatedIcon(CoffeeAnimatedDefinition)
export const AnimatedCopyIcon = /* @__PURE__ */ createAnimatedIcon(CopyAnimatedDefinition)
export const AnimatedCreditCardIcon = /* @__PURE__ */ createAnimatedIcon(
  CreditCardAnimatedDefinition
)
export const AnimatedCrownIcon = /* @__PURE__ */ createAnimatedIcon(CrownAnimatedDefinition)
export const AnimatedDatabaseIcon = /* @__PURE__ */ createAnimatedIcon(DatabaseAnimatedDefinition)
export const AnimatedDownloadIcon = /* @__PURE__ */ createAnimatedIcon(DownloadAnimatedDefinition)
export const AnimatedExternalLinkIcon = /* @__PURE__ */ createAnimatedIcon(
  ExternalLinkAnimatedDefinition
)
export const AnimatedEyeIcon = /* @__PURE__ */ createAnimatedIcon(EyeAnimatedDefinition)
export const AnimatedEyeOffIcon = /* @__PURE__ */ createAnimatedIcon(EyeOffAnimatedDefinition)
export const AnimatedFileTextIcon = /* @__PURE__ */ createAnimatedIcon(FileTextAnimatedDefinition)
export const AnimatedFilterIcon = /* @__PURE__ */ createAnimatedIcon(FilterAnimatedDefinition)
export const AnimatedFlagIcon = /* @__PURE__ */ createAnimatedIcon(FlagAnimatedDefinition)
export const AnimatedFolderIcon = /* @__PURE__ */ createAnimatedIcon(FolderAnimatedDefinition)
export const AnimatedFolderGit2Icon = /* @__PURE__ */ createAnimatedIcon(
  FolderGit2AnimatedDefinition
)
export const AnimatedFolderKanbanIcon = /* @__PURE__ */ createAnimatedIcon(
  FolderKanbanAnimatedDefinition
)
export const AnimatedFolderOpenIcon = /* @__PURE__ */ createAnimatedIcon(
  FolderOpenAnimatedDefinition
)
export const AnimatedGitBranchIcon = /* @__PURE__ */ createAnimatedIcon(GitBranchAnimatedDefinition)
export const AnimatedGlobeIcon = /* @__PURE__ */ createAnimatedIcon(GlobeAnimatedDefinition)
export const AnimatedGlobe2Icon = /* @__PURE__ */ createAnimatedIcon(Globe2AnimatedDefinition)
export const AnimatedGraduationCapIcon = /* @__PURE__ */ createAnimatedIcon(
  GraduationCapAnimatedDefinition
)
export const AnimatedHeartIcon = /* @__PURE__ */ createAnimatedIcon(HeartAnimatedDefinition)
export const AnimatedHistoryIcon = /* @__PURE__ */ createAnimatedIcon(HistoryAnimatedDefinition)
export const AnimatedHouseIcon = /* @__PURE__ */ createAnimatedIcon(HouseAnimatedDefinition)
export const AnimatedImagePlusIcon = /* @__PURE__ */ createAnimatedIcon(ImagePlusAnimatedDefinition)
export const AnimatedInfoIcon = /* @__PURE__ */ createAnimatedIcon(InfoAnimatedDefinition)
export const AnimatedKeyRoundIcon = /* @__PURE__ */ createAnimatedIcon(KeyRoundAnimatedDefinition)
export const AnimatedLayoutGridIcon = /* @__PURE__ */ createAnimatedIcon(
  LayoutGridAnimatedDefinition
)
export const AnimatedLink2Icon = /* @__PURE__ */ createAnimatedIcon(Link2AnimatedDefinition)
export const AnimatedLoader2Icon = /* @__PURE__ */ createAnimatedIcon(Loader2AnimatedDefinition)
export const AnimatedLockIcon = /* @__PURE__ */ createAnimatedIcon(LockAnimatedDefinition)
export const AnimatedLockKeyholeIcon = /* @__PURE__ */ createAnimatedIcon(
  LockKeyholeAnimatedDefinition
)
export const AnimatedLogInIcon = /* @__PURE__ */ createAnimatedIcon(LogInAnimatedDefinition)
export const AnimatedLogOutIcon = /* @__PURE__ */ createAnimatedIcon(LogOutAnimatedDefinition)
export const AnimatedMailIcon = /* @__PURE__ */ createAnimatedIcon(MailAnimatedDefinition)
export const AnimatedMapPinIcon = /* @__PURE__ */ createAnimatedIcon(MapPinAnimatedDefinition)
export const AnimatedMaximize2Icon = /* @__PURE__ */ createAnimatedIcon(Maximize2AnimatedDefinition)
export const AnimatedMegaphoneIcon = /* @__PURE__ */ createAnimatedIcon(MegaphoneAnimatedDefinition)
export const AnimatedMenuIcon = /* @__PURE__ */ createAnimatedIcon(MenuAnimatedDefinition)
export const AnimatedMessageCircleIcon = /* @__PURE__ */ createAnimatedIcon(
  MessageCircleAnimatedDefinition
)
export const AnimatedMessageSquareIcon = /* @__PURE__ */ createAnimatedIcon(
  MessageSquareAnimatedDefinition
)
export const AnimatedMessagesSquareIcon = /* @__PURE__ */ createAnimatedIcon(
  MessagesSquareAnimatedDefinition
)
export const AnimatedMicIcon = /* @__PURE__ */ createAnimatedIcon(MicAnimatedDefinition)
export const AnimatedMinusIcon = /* @__PURE__ */ createAnimatedIcon(MinusAnimatedDefinition)
export const AnimatedMonitorCogIcon = /* @__PURE__ */ createAnimatedIcon(
  MonitorCogAnimatedDefinition
)
export const AnimatedMoonIcon = /* @__PURE__ */ createAnimatedIcon(MoonAnimatedDefinition)
export const AnimatedMoreHorizontalIcon = /* @__PURE__ */ createAnimatedIcon(
  MoreHorizontalAnimatedDefinition
)
export const AnimatedPaperclipIcon = /* @__PURE__ */ createAnimatedIcon(PaperclipAnimatedDefinition)
export const AnimatedPauseIcon = /* @__PURE__ */ createAnimatedIcon(PauseAnimatedDefinition)
export const AnimatedPencilIcon = /* @__PURE__ */ createAnimatedIcon(PencilAnimatedDefinition)
export const AnimatedPenLineIcon = /* @__PURE__ */ createAnimatedIcon(PenLineAnimatedDefinition)
export const AnimatedPlayIcon = /* @__PURE__ */ createAnimatedIcon(PlayAnimatedDefinition)
export const AnimatedPlusIcon = /* @__PURE__ */ createAnimatedIcon(PlusAnimatedDefinition)
export const AnimatedRefreshCcwIcon = /* @__PURE__ */ createAnimatedIcon(
  RefreshCcwAnimatedDefinition
)
export const AnimatedRefreshCwIcon = /* @__PURE__ */ createAnimatedIcon(RefreshCwAnimatedDefinition)
export const AnimatedRocketIcon = /* @__PURE__ */ createAnimatedIcon(RocketAnimatedDefinition)
export const AnimatedRotateCcwIcon = /* @__PURE__ */ createAnimatedIcon(RotateCcwAnimatedDefinition)
export const AnimatedSaveIcon = /* @__PURE__ */ createAnimatedIcon(SaveAnimatedDefinition)
export const AnimatedSearchIcon = /* @__PURE__ */ createAnimatedIcon(SearchAnimatedDefinition)
export const AnimatedSendIcon = /* @__PURE__ */ createAnimatedIcon(SendAnimatedDefinition)
export const AnimatedServerCogIcon = /* @__PURE__ */ createAnimatedIcon(ServerCogAnimatedDefinition)
export const AnimatedSettingsIcon = /* @__PURE__ */ createAnimatedIcon(SettingsAnimatedDefinition)
export const AnimatedShare2Icon = /* @__PURE__ */ createAnimatedIcon(Share2AnimatedDefinition)
export const AnimatedShieldCheckIcon = /* @__PURE__ */ createAnimatedIcon(
  ShieldCheckAnimatedDefinition
)
export const AnimatedSlidersHorizontalIcon = /* @__PURE__ */ createAnimatedIcon(
  SlidersHorizontalAnimatedDefinition
)
export const AnimatedSmartphoneIcon = /* @__PURE__ */ createAnimatedIcon(
  SmartphoneAnimatedDefinition
)
export const AnimatedSparklesIcon = /* @__PURE__ */ createAnimatedIcon(SparklesAnimatedDefinition)
export const AnimatedSquareKanbanIcon = /* @__PURE__ */ createAnimatedIcon(
  SquareKanbanAnimatedDefinition
)
export const AnimatedSquareTerminalIcon = /* @__PURE__ */ createAnimatedIcon(
  SquareTerminalAnimatedDefinition
)
export const AnimatedStarIcon = /* @__PURE__ */ createAnimatedIcon(StarAnimatedDefinition)
export const AnimatedSunIcon = /* @__PURE__ */ createAnimatedIcon(SunAnimatedDefinition)
export const AnimatedThumbsUpIcon = /* @__PURE__ */ createAnimatedIcon(ThumbsUpAnimatedDefinition)
export const AnimatedTrash2Icon = /* @__PURE__ */ createAnimatedIcon(Trash2AnimatedDefinition)
export const AnimatedUploadIcon = /* @__PURE__ */ createAnimatedIcon(UploadAnimatedDefinition)
export const AnimatedUserPlusIcon = /* @__PURE__ */ createAnimatedIcon(UserPlusAnimatedDefinition)
export const AnimatedUserRoundIcon = /* @__PURE__ */ createAnimatedIcon(UserRoundAnimatedDefinition)
export const AnimatedUsersIcon = /* @__PURE__ */ createAnimatedIcon(UsersAnimatedDefinition)
export const AnimatedVolume2Icon = /* @__PURE__ */ createAnimatedIcon(Volume2AnimatedDefinition)
export const AnimatedWifiIcon = /* @__PURE__ */ createAnimatedIcon(WifiAnimatedDefinition)
export const AnimatedWrenchIcon = /* @__PURE__ */ createAnimatedIcon(WrenchAnimatedDefinition)
export const AnimatedXIcon = /* @__PURE__ */ createAnimatedIcon(XAnimatedDefinition)
export const AnimatedXCircleIcon = /* @__PURE__ */ createAnimatedIcon(XCircleAnimatedDefinition)
export const AnimatedZapIcon = /* @__PURE__ */ createAnimatedIcon(ZapAnimatedDefinition)
