// Generated by scripts/generate.mjs. Edit src/definitions instead.
import { createIcon } from './icon'
import {
  AlertCircleDefinition,
  AlertTriangleDefinition,
  ArrowDownDefinition,
  ArrowLeftDefinition,
  ArrowRightDefinition,
  ArrowUpDefinition,
  ArrowUpRightDefinition,
  BadgeCheckDefinition,
  BellDefinition,
  BellRingDefinition,
  BookmarkDefinition,
  BotDefinition,
  BriefcaseDefinition,
  Building2Definition,
  CalendarDaysDefinition,
  CameraDefinition,
  CheckDefinition,
  CheckCircle2Definition,
  ChevronDownDefinition,
  ChevronLeftDefinition,
  ChevronRightDefinition,
  ChevronsUpDownDefinition,
  ChevronUpDefinition,
  ClockDefinition,
  Clock3Definition,
  CloudUploadDefinition,
  Code2Definition,
  CoffeeDefinition,
  CopyDefinition,
  CreditCardDefinition,
  CrownDefinition,
  DatabaseDefinition,
  DownloadDefinition,
  ExternalLinkDefinition,
  EyeDefinition,
  EyeOffDefinition,
  FileTextDefinition,
  FilterDefinition,
  FlagDefinition,
  FolderDefinition,
  FolderGit2Definition,
  FolderKanbanDefinition,
  FolderOpenDefinition,
  GitBranchDefinition,
  GlobeDefinition,
  Globe2Definition,
  GraduationCapDefinition,
  HeartDefinition,
  HistoryDefinition,
  HouseDefinition,
  ImagePlusDefinition,
  InfoDefinition,
  KeyRoundDefinition,
  LayoutGridDefinition,
  Link2Definition,
  Loader2Definition,
  LockDefinition,
  LockKeyholeDefinition,
  LogInDefinition,
  LogOutDefinition,
  MailDefinition,
  MapPinDefinition,
  Maximize2Definition,
  MegaphoneDefinition,
  MenuDefinition,
  MessageCircleDefinition,
  MessageSquareDefinition,
  MessagesSquareDefinition,
  MicDefinition,
  MinusDefinition,
  MonitorCogDefinition,
  MoonDefinition,
  MoreHorizontalDefinition,
  PaperclipDefinition,
  PauseDefinition,
  PencilDefinition,
  PenLineDefinition,
  PlayDefinition,
  PlusDefinition,
  RefreshCcwDefinition,
  RefreshCwDefinition,
  RocketDefinition,
  RotateCcwDefinition,
  SaveDefinition,
  SearchDefinition,
  SendDefinition,
  ServerCogDefinition,
  SettingsDefinition,
  Share2Definition,
  ShieldCheckDefinition,
  SlidersHorizontalDefinition,
  SmartphoneDefinition,
  SparklesDefinition,
  SquareKanbanDefinition,
  SquareTerminalDefinition,
  StarDefinition,
  SunDefinition,
  ThumbsUpDefinition,
  Trash2Definition,
  UploadDefinition,
  UserPlusDefinition,
  UserRoundDefinition,
  UsersDefinition,
  Volume2Definition,
  WifiDefinition,
  WrenchDefinition,
  XDefinition,
  XCircleDefinition,
  ZapDefinition,
} from './generated/definitions'
export { Icon } from './icon'
export type { IconProps, IconDefinition, IconCategory } from './types'

export const AlertCircleIcon = /* @__PURE__ */ createIcon(AlertCircleDefinition)
export const AlertTriangleIcon = /* @__PURE__ */ createIcon(AlertTriangleDefinition)
export const ArrowDownIcon = /* @__PURE__ */ createIcon(ArrowDownDefinition)
export const ArrowLeftIcon = /* @__PURE__ */ createIcon(ArrowLeftDefinition)
export const ArrowRightIcon = /* @__PURE__ */ createIcon(ArrowRightDefinition)
export const ArrowUpIcon = /* @__PURE__ */ createIcon(ArrowUpDefinition)
export const ArrowUpRightIcon = /* @__PURE__ */ createIcon(ArrowUpRightDefinition)
export const BadgeCheckIcon = /* @__PURE__ */ createIcon(BadgeCheckDefinition)
export const BellIcon = /* @__PURE__ */ createIcon(BellDefinition)
export const BellRingIcon = /* @__PURE__ */ createIcon(BellRingDefinition)
export const BookmarkIcon = /* @__PURE__ */ createIcon(BookmarkDefinition)
export const BotIcon = /* @__PURE__ */ createIcon(BotDefinition)
export const BriefcaseIcon = /* @__PURE__ */ createIcon(BriefcaseDefinition)
export const Building2Icon = /* @__PURE__ */ createIcon(Building2Definition)
export const CalendarDaysIcon = /* @__PURE__ */ createIcon(CalendarDaysDefinition)
export const CameraIcon = /* @__PURE__ */ createIcon(CameraDefinition)
export const CheckIcon = /* @__PURE__ */ createIcon(CheckDefinition)
export const CheckCircle2Icon = /* @__PURE__ */ createIcon(CheckCircle2Definition)
export const ChevronDownIcon = /* @__PURE__ */ createIcon(ChevronDownDefinition)
export const ChevronLeftIcon = /* @__PURE__ */ createIcon(ChevronLeftDefinition)
export const ChevronRightIcon = /* @__PURE__ */ createIcon(ChevronRightDefinition)
export const ChevronsUpDownIcon = /* @__PURE__ */ createIcon(ChevronsUpDownDefinition)
export const ChevronUpIcon = /* @__PURE__ */ createIcon(ChevronUpDefinition)
export const ClockIcon = /* @__PURE__ */ createIcon(ClockDefinition)
export const Clock3Icon = /* @__PURE__ */ createIcon(Clock3Definition)
export const CloudUploadIcon = /* @__PURE__ */ createIcon(CloudUploadDefinition)
export const Code2Icon = /* @__PURE__ */ createIcon(Code2Definition)
export const CoffeeIcon = /* @__PURE__ */ createIcon(CoffeeDefinition)
export const CopyIcon = /* @__PURE__ */ createIcon(CopyDefinition)
export const CreditCardIcon = /* @__PURE__ */ createIcon(CreditCardDefinition)
export const CrownIcon = /* @__PURE__ */ createIcon(CrownDefinition)
export const DatabaseIcon = /* @__PURE__ */ createIcon(DatabaseDefinition)
export const DownloadIcon = /* @__PURE__ */ createIcon(DownloadDefinition)
export const ExternalLinkIcon = /* @__PURE__ */ createIcon(ExternalLinkDefinition)
export const EyeIcon = /* @__PURE__ */ createIcon(EyeDefinition)
export const EyeOffIcon = /* @__PURE__ */ createIcon(EyeOffDefinition)
export const FileTextIcon = /* @__PURE__ */ createIcon(FileTextDefinition)
export const FilterIcon = /* @__PURE__ */ createIcon(FilterDefinition)
export const FlagIcon = /* @__PURE__ */ createIcon(FlagDefinition)
export const FolderIcon = /* @__PURE__ */ createIcon(FolderDefinition)
export const FolderGit2Icon = /* @__PURE__ */ createIcon(FolderGit2Definition)
export const FolderKanbanIcon = /* @__PURE__ */ createIcon(FolderKanbanDefinition)
export const FolderOpenIcon = /* @__PURE__ */ createIcon(FolderOpenDefinition)
export const GitBranchIcon = /* @__PURE__ */ createIcon(GitBranchDefinition)
export const GlobeIcon = /* @__PURE__ */ createIcon(GlobeDefinition)
export const Globe2Icon = /* @__PURE__ */ createIcon(Globe2Definition)
export const GraduationCapIcon = /* @__PURE__ */ createIcon(GraduationCapDefinition)
export const HeartIcon = /* @__PURE__ */ createIcon(HeartDefinition)
export const HistoryIcon = /* @__PURE__ */ createIcon(HistoryDefinition)
export const HouseIcon = /* @__PURE__ */ createIcon(HouseDefinition)
export const ImagePlusIcon = /* @__PURE__ */ createIcon(ImagePlusDefinition)
export const InfoIcon = /* @__PURE__ */ createIcon(InfoDefinition)
export const KeyRoundIcon = /* @__PURE__ */ createIcon(KeyRoundDefinition)
export const LayoutGridIcon = /* @__PURE__ */ createIcon(LayoutGridDefinition)
export const Link2Icon = /* @__PURE__ */ createIcon(Link2Definition)
export const Loader2Icon = /* @__PURE__ */ createIcon(Loader2Definition)
export const LockIcon = /* @__PURE__ */ createIcon(LockDefinition)
export const LockKeyholeIcon = /* @__PURE__ */ createIcon(LockKeyholeDefinition)
export const LogInIcon = /* @__PURE__ */ createIcon(LogInDefinition)
export const LogOutIcon = /* @__PURE__ */ createIcon(LogOutDefinition)
export const MailIcon = /* @__PURE__ */ createIcon(MailDefinition)
export const MapPinIcon = /* @__PURE__ */ createIcon(MapPinDefinition)
export const Maximize2Icon = /* @__PURE__ */ createIcon(Maximize2Definition)
export const MegaphoneIcon = /* @__PURE__ */ createIcon(MegaphoneDefinition)
export const MenuIcon = /* @__PURE__ */ createIcon(MenuDefinition)
export const MessageCircleIcon = /* @__PURE__ */ createIcon(MessageCircleDefinition)
export const MessageSquareIcon = /* @__PURE__ */ createIcon(MessageSquareDefinition)
export const MessagesSquareIcon = /* @__PURE__ */ createIcon(MessagesSquareDefinition)
export const MicIcon = /* @__PURE__ */ createIcon(MicDefinition)
export const MinusIcon = /* @__PURE__ */ createIcon(MinusDefinition)
export const MonitorCogIcon = /* @__PURE__ */ createIcon(MonitorCogDefinition)
export const MoonIcon = /* @__PURE__ */ createIcon(MoonDefinition)
export const MoreHorizontalIcon = /* @__PURE__ */ createIcon(MoreHorizontalDefinition)
export const PaperclipIcon = /* @__PURE__ */ createIcon(PaperclipDefinition)
export const PauseIcon = /* @__PURE__ */ createIcon(PauseDefinition)
export const PencilIcon = /* @__PURE__ */ createIcon(PencilDefinition)
export const PenLineIcon = /* @__PURE__ */ createIcon(PenLineDefinition)
export const PlayIcon = /* @__PURE__ */ createIcon(PlayDefinition)
export const PlusIcon = /* @__PURE__ */ createIcon(PlusDefinition)
export const RefreshCcwIcon = /* @__PURE__ */ createIcon(RefreshCcwDefinition)
export const RefreshCwIcon = /* @__PURE__ */ createIcon(RefreshCwDefinition)
export const RocketIcon = /* @__PURE__ */ createIcon(RocketDefinition)
export const RotateCcwIcon = /* @__PURE__ */ createIcon(RotateCcwDefinition)
export const SaveIcon = /* @__PURE__ */ createIcon(SaveDefinition)
export const SearchIcon = /* @__PURE__ */ createIcon(SearchDefinition)
export const SendIcon = /* @__PURE__ */ createIcon(SendDefinition)
export const ServerCogIcon = /* @__PURE__ */ createIcon(ServerCogDefinition)
export const SettingsIcon = /* @__PURE__ */ createIcon(SettingsDefinition)
export const Share2Icon = /* @__PURE__ */ createIcon(Share2Definition)
export const ShieldCheckIcon = /* @__PURE__ */ createIcon(ShieldCheckDefinition)
export const SlidersHorizontalIcon = /* @__PURE__ */ createIcon(SlidersHorizontalDefinition)
export const SmartphoneIcon = /* @__PURE__ */ createIcon(SmartphoneDefinition)
export const SparklesIcon = /* @__PURE__ */ createIcon(SparklesDefinition)
export const SquareKanbanIcon = /* @__PURE__ */ createIcon(SquareKanbanDefinition)
export const SquareTerminalIcon = /* @__PURE__ */ createIcon(SquareTerminalDefinition)
export const StarIcon = /* @__PURE__ */ createIcon(StarDefinition)
export const SunIcon = /* @__PURE__ */ createIcon(SunDefinition)
export const ThumbsUpIcon = /* @__PURE__ */ createIcon(ThumbsUpDefinition)
export const Trash2Icon = /* @__PURE__ */ createIcon(Trash2Definition)
export const UploadIcon = /* @__PURE__ */ createIcon(UploadDefinition)
export const UserPlusIcon = /* @__PURE__ */ createIcon(UserPlusDefinition)
export const UserRoundIcon = /* @__PURE__ */ createIcon(UserRoundDefinition)
export const UsersIcon = /* @__PURE__ */ createIcon(UsersDefinition)
export const Volume2Icon = /* @__PURE__ */ createIcon(Volume2Definition)
export const WifiIcon = /* @__PURE__ */ createIcon(WifiDefinition)
export const WrenchIcon = /* @__PURE__ */ createIcon(WrenchDefinition)
export const XIcon = /* @__PURE__ */ createIcon(XDefinition)
export const XCircleIcon = /* @__PURE__ */ createIcon(XCircleDefinition)
export const ZapIcon = /* @__PURE__ */ createIcon(ZapDefinition)
