// Generated by scripts/generate.mjs. Edit src/definitions instead.
import { createIcon } from './icon'
import {
  AlertCircleDefinition,
  AlertTriangleDefinition,
  ArrowDownDefinition,
  ArrowLeftDefinition,
  ArrowRightDefinition,
  ArrowUpDefinition,
  ArrowUpRightDefinition,
  BellDefinition,
  BriefcaseDefinition,
  CalendarDaysDefinition,
  CheckDefinition,
  CheckCircle2Definition,
  ChevronDownDefinition,
  ChevronLeftDefinition,
  ChevronRightDefinition,
  ChevronsUpDownDefinition,
  Clock3Definition,
  CopyDefinition,
  CreditCardDefinition,
  DatabaseDefinition,
  DownloadDefinition,
  ExternalLinkDefinition,
  FileTextDefinition,
  FolderDefinition,
  Globe2Definition,
  GraduationCapDefinition,
  HeartDefinition,
  HouseDefinition,
  ImagePlusDefinition,
  KeyRoundDefinition,
  Link2Definition,
  Loader2Definition,
  LockDefinition,
  LockKeyholeDefinition,
  LogOutDefinition,
  MapPinDefinition,
  MenuDefinition,
  MessageCircleDefinition,
  MessagesSquareDefinition,
  MoreHorizontalDefinition,
  PencilDefinition,
  PlusDefinition,
  RefreshCcwDefinition,
  RefreshCwDefinition,
  RocketDefinition,
  RotateCcwDefinition,
  SearchDefinition,
  SendDefinition,
  SettingsDefinition,
  Share2Definition,
  ShieldCheckDefinition,
  SlidersHorizontalDefinition,
  SmartphoneDefinition,
  SparklesDefinition,
  StarDefinition,
  Trash2Definition,
  UploadDefinition,
  UserRoundDefinition,
  UsersDefinition,
  XDefinition,
} from './generated/definitions'
export { Icon } from './icon'
export type { IconProps, IconDefinition, IconCategory } from './types'

export const AlertCircleIcon = /* @__PURE__ */ createIcon(AlertCircleDefinition)
export const AlertTriangleIcon = /* @__PURE__ */ createIcon(AlertTriangleDefinition)
export const ArrowDownIcon = /* @__PURE__ */ createIcon(ArrowDownDefinition)
export const ArrowLeftIcon = /* @__PURE__ */ createIcon(ArrowLeftDefinition)
export const ArrowRightIcon = /* @__PURE__ */ createIcon(ArrowRightDefinition)
export const ArrowUpIcon = /* @__PURE__ */ createIcon(ArrowUpDefinition)
export const ArrowUpRightIcon = /* @__PURE__ */ createIcon(ArrowUpRightDefinition)
export const BellIcon = /* @__PURE__ */ createIcon(BellDefinition)
export const BriefcaseIcon = /* @__PURE__ */ createIcon(BriefcaseDefinition)
export const CalendarDaysIcon = /* @__PURE__ */ createIcon(CalendarDaysDefinition)
export const CheckIcon = /* @__PURE__ */ createIcon(CheckDefinition)
export const CheckCircle2Icon = /* @__PURE__ */ createIcon(CheckCircle2Definition)
export const ChevronDownIcon = /* @__PURE__ */ createIcon(ChevronDownDefinition)
export const ChevronLeftIcon = /* @__PURE__ */ createIcon(ChevronLeftDefinition)
export const ChevronRightIcon = /* @__PURE__ */ createIcon(ChevronRightDefinition)
export const ChevronsUpDownIcon = /* @__PURE__ */ createIcon(ChevronsUpDownDefinition)
export const Clock3Icon = /* @__PURE__ */ createIcon(Clock3Definition)
export const CopyIcon = /* @__PURE__ */ createIcon(CopyDefinition)
export const CreditCardIcon = /* @__PURE__ */ createIcon(CreditCardDefinition)
export const DatabaseIcon = /* @__PURE__ */ createIcon(DatabaseDefinition)
export const DownloadIcon = /* @__PURE__ */ createIcon(DownloadDefinition)
export const ExternalLinkIcon = /* @__PURE__ */ createIcon(ExternalLinkDefinition)
export const FileTextIcon = /* @__PURE__ */ createIcon(FileTextDefinition)
export const FolderIcon = /* @__PURE__ */ createIcon(FolderDefinition)
export const Globe2Icon = /* @__PURE__ */ createIcon(Globe2Definition)
export const GraduationCapIcon = /* @__PURE__ */ createIcon(GraduationCapDefinition)
export const HeartIcon = /* @__PURE__ */ createIcon(HeartDefinition)
export const HouseIcon = /* @__PURE__ */ createIcon(HouseDefinition)
export const ImagePlusIcon = /* @__PURE__ */ createIcon(ImagePlusDefinition)
export const KeyRoundIcon = /* @__PURE__ */ createIcon(KeyRoundDefinition)
export const Link2Icon = /* @__PURE__ */ createIcon(Link2Definition)
export const Loader2Icon = /* @__PURE__ */ createIcon(Loader2Definition)
export const LockIcon = /* @__PURE__ */ createIcon(LockDefinition)
export const LockKeyholeIcon = /* @__PURE__ */ createIcon(LockKeyholeDefinition)
export const LogOutIcon = /* @__PURE__ */ createIcon(LogOutDefinition)
export const MapPinIcon = /* @__PURE__ */ createIcon(MapPinDefinition)
export const MenuIcon = /* @__PURE__ */ createIcon(MenuDefinition)
export const MessageCircleIcon = /* @__PURE__ */ createIcon(MessageCircleDefinition)
export const MessagesSquareIcon = /* @__PURE__ */ createIcon(MessagesSquareDefinition)
export const MoreHorizontalIcon = /* @__PURE__ */ createIcon(MoreHorizontalDefinition)
export const PencilIcon = /* @__PURE__ */ createIcon(PencilDefinition)
export const PlusIcon = /* @__PURE__ */ createIcon(PlusDefinition)
export const RefreshCcwIcon = /* @__PURE__ */ createIcon(RefreshCcwDefinition)
export const RefreshCwIcon = /* @__PURE__ */ createIcon(RefreshCwDefinition)
export const RocketIcon = /* @__PURE__ */ createIcon(RocketDefinition)
export const RotateCcwIcon = /* @__PURE__ */ createIcon(RotateCcwDefinition)
export const SearchIcon = /* @__PURE__ */ createIcon(SearchDefinition)
export const SendIcon = /* @__PURE__ */ createIcon(SendDefinition)
export const SettingsIcon = /* @__PURE__ */ createIcon(SettingsDefinition)
export const Share2Icon = /* @__PURE__ */ createIcon(Share2Definition)
export const ShieldCheckIcon = /* @__PURE__ */ createIcon(ShieldCheckDefinition)
export const SlidersHorizontalIcon = /* @__PURE__ */ createIcon(SlidersHorizontalDefinition)
export const SmartphoneIcon = /* @__PURE__ */ createIcon(SmartphoneDefinition)
export const SparklesIcon = /* @__PURE__ */ createIcon(SparklesDefinition)
export const StarIcon = /* @__PURE__ */ createIcon(StarDefinition)
export const Trash2Icon = /* @__PURE__ */ createIcon(Trash2Definition)
export const UploadIcon = /* @__PURE__ */ createIcon(UploadDefinition)
export const UserRoundIcon = /* @__PURE__ */ createIcon(UserRoundDefinition)
export const UsersIcon = /* @__PURE__ */ createIcon(UsersDefinition)
export const XIcon = /* @__PURE__ */ createIcon(XDefinition)
