import { writeFileSync, mkdirSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'
import { actionIcons } from '../src/definitions/actions.ts'
import { objectIcons } from '../src/definitions/objects.ts'

const root = fileURLToPath(new URL('../src/', import.meta.url))
const icons = [...actionIcons, ...objectIcons].sort((a, b) => a.name.localeCompare(b.name))
if (new Set(icons.map((icon) => icon.name)).size !== icons.length)
  throw new Error('Duplicate icon name')
const header = '// Generated by scripts/generate.mjs. Edit src/definitions instead.\n'
mkdirSync(`${root}/generated`, { recursive: true })
// Independent constants let consumers tree-shake drawings AND motion data for unused icons.
writeFileSync(
  `${root}/generated/definitions.ts`,
  header +
    'import type { IconDefinition } from "../types"\n\n' +
    icons
      .map(
        (icon) =>
          `export const ${icon.name}Definition: IconDefinition = ${JSON.stringify({ ...icon, motion: [] }, null, 2)}\nexport const ${icon.name}AnimatedDefinition: IconDefinition = ${JSON.stringify(icon, null, 2)}\n`
      )
      .join('\n')
)
const imports = icons.map((icon) => `${icon.name}Definition`).join(', ')
const animatedImports = icons.map((icon) => `${icon.name}AnimatedDefinition`).join(', ')
writeFileSync(
  `${root}/index.ts`,
  header +
    `import { createIcon } from './icon'\nimport { ${imports} } from './generated/definitions'\nexport { Icon } from './icon'\nexport type { IconProps, IconDefinition, IconCategory } from './types'\n\n` +
    icons
      .map(
        (icon) =>
          `export const ${icon.name}Icon = /* @__PURE__ */ createIcon(${icon.name}Definition)`
      )
      .join('\n') +
    '\n'
)
writeFileSync(
  `${root}/animated.ts`,
  `'use client'\n\n` +
    header +
    `import { createAnimatedIcon } from './create-animated-icon'\nimport { ${animatedImports} } from './generated/definitions'\nexport { AnimatedIcon } from './create-animated-icon'\nexport type { AnimatedIconProps } from './types'\n\n` +
    icons
      .map(
        (icon) =>
          `export const Animated${icon.name}Icon = /* @__PURE__ */ createAnimatedIcon(${icon.name}AnimatedDefinition)`
      )
      .join('\n') +
    '\n'
)
writeFileSync(
  `${root}/catalog.ts`,
  header +
    `import { ${animatedImports} } from './generated/definitions'\nexport const iconCatalog = [${animatedImports}] as const\n`
)
console.log(`Generated ${icons.length} static and animated icons.`)

const config = await resolveConfig(root)
for (const file of ['generated/definitions.ts', 'index.ts', 'animated.ts', 'catalog.ts']) {
  const path = `${root}/${file}`
  writeFileSync(path, await format(readFileSync(path, 'utf8'), { ...config, parser: 'typescript' }))
}
